Resources:
  GraphqlNone:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: Role_${self:service}_${self:provider.stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowLambdaToInvokeOtherLambda${self:provider.environment.APP}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:InvokeAsync
                Resource: "*"
        - PolicyName: RecordProgressInLogs${self:provider.environment.APP}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: S3ReadWrite${self:provider.environment.APP}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${AttachmentsBucket}/*'
        - PolicyName: CognitoAdmin${self:provider.environment.APP}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminCreateUser
                  - cognito-idp:AdminDeleteUser
                  - cognito-idp:AdminSetUserPassword
                  - cognito-idp:AdminUpdateUserAttributes
                Resource: "*"
        - PolicyName: DynamoReadWrite${self:provider.environment.APP}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:CreateTable
                  - dynamodb:Delete*
                  - dynamodb:Update*
                  - dynamodb:PutItem
                  - dynamodb:BatchGetItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:*:*:table/${AdminTable}*'
                  - !Sub 'arn:aws:dynamodb:*:*:table/${CompanyTable}*'
                  - !Sub 'arn:aws:dynamodb:*:*:table/${UserTable}*'
                  - !Sub 'arn:aws:dynamodb:*:*:table/${RequestTable}*'
